### ISSUE TITLE
Module Features not found

### ISSUE THREAD

**Issue by antirek** [wppconnect-team/wppconnect#1027]
## Description

on load error:

```
Unhandled Rejection: Error: "Module Features not found with e=>{var t,r;return(null===(t=e.GK)||void 0===t?void 0:t.supportsFeature)||(null===(r=e.default)||void 0===r?void 0:r.supportsFeature)}"
     at /usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:106:31
     at step (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
     at Object.next (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
     at fulfilled (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
JS Stack: Error: "Module Features not found with e=>{var t,r;return(null===(t=e.GK)||void 0===t?void 0:t.supportsFeature)||(null===(r=e.default)||void 0===r?void 0:r.supportsFeature)}"
     at /usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:103:33
     at step (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
     at Object.next (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
     at fulfilled (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

## Environment

- **WPPConnect version(s):** 1.12.8
- **WA-JS version(s):** 1.2.5
- **Browser:** Chrome 99
- **OS:** Ubuntu 20
- **Node version:** Node 16
- **WhatsApp version:** 2.2214.9
- **MultiDevice (BETA):** yes

**Comment by antirek** [comment]
also same eror on client.checkNumberStatus()

**Comment by edgardmessias** [comment]
Solved with latest release

https://github.com/wppconnect-team/wppconnect/releases/tag/v1.13.0
