### ISSUE TITLE
Método sendLocation  Invalid value at currentMsg.lng: value is invalid

### ISSUE THREAD

**Issue by icleitoncosta** [wppconnect-team/wppconnect#1117]
## Description

Quando tento enviar a localização através do método sendLocation o mesmo não vai
Mensagem apresentada:

## Environment

- **WPPConnect version(s):** 1.13.1
- **WA-JS version(s):** 2.2.1
- **Browser:** Chrome ZZ 
- **OS:** Ubuntu 20.04
- **Node version:** Node 16
- **WhatsApp version:** 2.2214.12
- **MultiDevice (BETA):** yes

## Steps to Reproduce

No caso eu só tento enviar e já é apresentado o erro:
Parametros passados:
5521967865110@c.us //ChatId
-22.9522592 //lat
-43.2118227 //lng

## Log Output

```
Error: Invalid value at currentMsg.lng: value is invalid
    at /home/sites/titanwhats-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:106:31
    at step (/home/sites/titanwhats-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/home/sites/titanwhats-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/home/sites/titanwhats-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
JS Stack: TypeError: Invalid value at currentMsg.lng: value is invalid
    at t.checkValid (https://web.whatsapp.com/bootstrap_qr.15b07f37ecbe5a626367.js:5:279277)
    at t.encodeProtobuf (https://web.whatsapp.com/bootstrap_qr.15b07f37ecbe5a626367.js:5:286176)
    at https://web.whatsapp.com/bootstrap_qr.15b07f37ecbe5a626367.js:70:37647
    at t.convertToMessageRowType (https://web.whatsapp.com/bootstrap_qr.15b07f37ecbe5a626367.js:70:37717)
    at https://web.whatsapp.com/bootstrap_qr.15b07f37ecbe5a626367.js:70:32012
    at Array.map (<anonymous>)
    at https://web.whatsapp.com/bootstrap_qr.15b07f37ecbe5a626367.js:70:31962
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.6ce3b7f48ca2444bd7bf.js:2:65356)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.6ce3b7f48ca2444bd7bf.js:2:65567)
error: 2022-05-24T22:42:28.520Z Invalid value at currentMsg.lng: value is invalid - Error: Invalid value at currentMsg.lng: value is invalid
    at /home/sites/titanwhats-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:106:31
    at step (/home/sites/titanwhats-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/home/sites/titanwhats-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/home/sites/titanwhats-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
JS Stack: TypeError: Invalid value at currentMsg.lng: value is invalid
    at t.checkValid (https://web.whatsapp.com/bootstrap_qr.15b07f37ecbe5a626367.js:5:279277)
    at t.encodeProtobuf (https://web.whatsapp.com/bootstrap_qr.15b07f37ecbe5a626367.js:5:286176)
    at https://web.whatsapp.com/bootstrap_qr.15b07f37ecbe5a626367.js:70:37647
    at t.convertToMessageRowType (https://web.whatsapp.com/bootstrap_qr.15b07f37ecbe5a626367.js:70:37717)
    at https://web.whatsapp.com/bootstrap_qr.15b07f37ecbe5a626367.js:70:32012
    at Array.map (<anonymous>)
    at https://web.whatsapp.com/bootstrap_qr.15b07f37ecbe5a626367.js:70:31962
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.6ce3b7f48ca2444bd7bf.js:2:65356)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.6ce3b7f48ca2444bd7bf.js:2:65567)
```

**Comment by edgardmessias** [comment]
Como você está passando a localização? Como string ou como float?
