### ISSUE TITLE
Error: Protocol error (Runtime.callFunctionOn): Promise was collected

### ISSUE THREAD

**Issue by icleitoncosta** [wppconnect-team/wppconnect#1160]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**

1. Search through the repo's previous issues x
2. Read through the readme at least once x
3. Search the docs for the feature you're looking for x 

Ola, estou tendo o seguinte erro em todas as mensagens de texto que envio, depois da ultima atualização:

```
ProtocolError: Protocol error (Runtime.callFunctionOn): Promise was collected
    at /home/node/server/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230:24
    at new Promise (<anonymous>)
    at CDPSession.send (/home/node/server/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:16)
    at ExecutionContext._evaluateInternal (/home/node/server/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50)
    at ExecutionContext.evaluate (/home/node/server/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)
    at DOMWorld.evaluate (/home/node/server/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:97:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  originalMessage: 'Promise was collected'
}
```
Codigo que executo na LIB:
Lembrando que a mensagem chega corretamente no cliente, e nao da nenhum problema significativo ate o momento

 ```
                       await client
                        .sendText(to, text)
                        .then((result) => {
                            resolve(result)
                        })
                        .catch((erro) => {
                            reject(erro)
                            console.error('Error when sending: ', erro); 
                        });
```

We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---

- Documentation: https://wppconnect-team.github.io/wppconnect/
- Discord: https://discord.gg/qCJ95FVbzR
- WhatsApp Group: [https://chat.whatsapp.com/EGLVbeFGgt40OkbOCX8Sei]
- Also have a look at the readme for more information on how to get support:

**Comment by icleitoncosta** [comment]
É algum erro meu interno, por isso irei fechar a Issue

**Comment by Sansekai** [comment]
@icleitoncosta What is the problem? I also experienced this problem but couldn't find a solution

**Comment by fernandomondo** [comment]
@icleitoncosta eu pego este erro exporadicamente. Qual foi a solução?
