### ISSUE TITLE
Send File not working in WA 2.2220.8

### ISSUE THREAD

**Issue by veracity-ind** [wppconnect-team/wppconnect#1161]
Send file is not working with updated wa web version

## Environment

- **WA-JS version(s):* *2.2220.8
- **Browser:** Chrome 
- **OS:** OSX 
- **MultiDevice (BETA):** yes

## Steps to Reproduce

client.sendFile('9xxxxxxxx@c.us', 'file.jpg')
      .then((result) => {
        console.log('Result: ', result); //return object success
      })
      .catch((erro) => {
        console.error('Error when sending: ', erro); //return object error
      });

## Log Output
Error when sending: Error: Cannot read properties of undefined (reading '0')
at /Users/veracity/work/code/internet/wa/wppconnect/dist/api/helpers/evaluate-and-return.js:106:31
at step (/Users/veracity/work/code/internet/wa/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
at Object.next (/Users/veracity/work/code/internet/wa/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
at fulfilled (/Users/veracity/work/code/internet/wa/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
at processTicksAndRejections (/Users/veracity/work/code/internet/wa/wppconnect/lib/internal/process/task_queues.js:96:5)
JS Stack: TypeError: Cannot read properties of undefined (reading '0')
at Object. (/Users/veracity/work/code/internet/wa/wppconnect/dist/lib/wapi/wapi.js:1:31009)
at Generator.next ()
at ye (/Users/veracity/work/code/internet/wa/wppconnect/dist/lib/wapi/wapi.js:1:30092)
at a (/Users/veracity/work/code/internet/wa/wppconnect/dist/lib/wapi/wapi.js:1:30296)
at W (https://web.whatsapp.com/bootstrap_qr.a817218351c7d3e5be74.js:32:83013)
at MutationObserver.x (https://web.whatsapp.com/bootstrap_qr.a817218351c7d3e5be74.js:32:79590) {stack: 'Error: Cannot read properties of undefined (r…ootstrap_qr.a817218351c7d3e5be74.js:32:79590)', message: 'Cannot read properties of undefined (reading '0')'}

**Comment by edgardmessias** [comment]
Closed by https://github.com/wppconnect-team/wppconnect/releases/tag/v1.14.0
