### ISSUE TITLE
wppconnect: skewMS error

### ISSUE THREAD

**Issue by antirek** [wppconnect-team/wppconnect#1363]
## Description

Update wa.js to latest 2.13.0 
receive error on send text message
use wa 2.2236.10 

send via wa 2.2238.5-beta - message was send

`````
err: {
   name: 'Error',
   message: "Cannot read properties of undefined (reading 'skewMS')",
   err: Error: Cannot read properties of undefined (reading 'skewMS')
       at /usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:106:31
       at step (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
       at Object.next (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
       at fulfilled (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (node:internal/process/task_queues:96:5)
   JS Stack: TypeError: Cannot read properties of undefined (reading 'skewMS')
       at globalUnixTime (https://web.whatsapp.com/bootstrap_qr.ff6e73954c8d5881bcf4.js:57:47135)
       at t.prepareRawMessage (/usr/src/app/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:145578)
       at t.sendRawMessage (/usr/src/app/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:154727)
       at async t.sendTextMessage (/usr/src/app/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:155976)
       at async pptr://__puppeteer_evaluation_script__:56:26
 }
`````

## Environment

- **WPPConnect version(s):** 1.17.0
- **WA-JS version(s):** 2.13.0
- **Browser:** Chrome 106
- **OS:** Ubuntu 20.04
- **Node version:** Node 16.15.1
- **WhatsApp version:** 2.2236.10
- **MultiDevice (BETA):** yes

**Comment by zindi-br** [comment]
i'm having the same problem. After calling 1.17.0 and setting whatsappVersion to '2.2230.15'

**Comment by jesusvalverde** [comment]
try to  WhatsApp WEB version: 2.2238.6

**Comment by jesusvalverde** [comment]
Same

**Comment by edgardmessias** [comment]
Fixed with latest wa-js

https://github.com/wppconnect-team/wa-js/releases/tag/v2.13.1

**Comment by antirek** [comment]
@edgardmessias thanks ))
