### ISSUE TITLE
Session is not working

### ISSUE THREAD

**Issue by rajenpal033** [wppconnect-team/wppconnect#1423]
After logged in once and script stopped, from next time it's neither prompting QR nor continuing with previous session. There is some error:
```
info:
  _       ______  ____  ______                            __
  | |     / / __ \/ __ \/ ____/___  ____  ____  ___  _____/ /_
  | | /| / / /_/ / /_/ / /   / __ \/ __ \/ __ \/ _ \/ ___/ __/
  | |/ |/ / ____/ ____/ /___/ /_/ / / / / / / /  __/ /__/ /_
  |__/|__/_/   /_/    \____/\____/_/ /_/_/ /_/\___/\___/\__/
info:     Checking for updates
info:     You're up to date
info:     [XXXXX:browser] Using browser folder '/var/tokens/XXXXX'
info:     [XXXXX:browser] Initializing browser...
http:     [XXXXX:browser] checking headless...
http:     [XXXXX:browser] headless option is active, browser hidden
info:     [XXXXX:client] Initializing...
http:     [XXXXX:client] Waiting page load
verbose:  [XXXXX:token] Injecting session token
verbose:  [XXXXX:client] Setting WhatsApp WEB version to 2.2234.x
verbose:  [XXXXX:client] Loading WhatsApp WEB
verbose:  [XXXXX:client] WhatsApp WEB loaded
verbose:  [XXXXX:page] Page loaded
verbose:  [XXXXX:client] Injecting wapi.js
verbose:  [XXXXX:client] wapi.js injected
verbose:  [XXXXX:token] Updating session token
debug:    [XXXXX:client] Exposing onMessage function
verbose:  [XXXXX:token] Session token updated
http:     [XXXXX:client] Checking is logged...
info:     [XXXXX:client] WhatsApp WEB version: 2.2234.13
info:     [XXXXX:client] WA-JS version: 2.15.2
info:     [XXXXX:client] Auto close configured to 60s
http:     [XXXXX:client] Authenticated
Status Session:  isLogged
Session name:  XXXXX
debug:    [XXXXX:client] Exposing onAnyMessage function
debug:    [XXXXX:client] Exposing onAck function
debug:    [XXXXX:client] Exposing onNotificationMessage function
debug:    [XXXXX:client] Exposing onParticipantsChanged function
debug:    [XXXXX:client] Exposing onStateChange function
debug:    [XXXXX:client] Exposing onStreamChange function
debug:    [XXXXX:client] Exposing onIncomingCall function
debug:    [XXXXX:client] Exposing onInterfaceChange function
debug:    [XXXXX:client] Exposing onPresenceChanged function
debug:    [XXXXX:client] Exposing onLiveLocation function
debug:    [XXXXX:client] Exposing onAddedToGroup function
debug:    [XXXXX:client] Exposing onRevokedMessage function
debug:    [XXXXX:client] Exposing onReactionMessage function
http:     [XXXXX:client] Current state: SYNCING (CONNECTING)
info:     [XXXXX:client] Auto close configured to 60s
http:     [XXXXX:client] Checking phone is connected...
http:     [XXXXX:client] Auto close remain: 50s
http:     [XXXXX:client] Auto close remain: 40s
http:     [XXXXX:client] Auto close remain: 30s
http:     [XXXXX:client] Auto close remain: 20s
http:     [XXXXX:client] Auto close remain: 10s
http:     [XXXXX:client] Auto close remain: 5s
http:     [XXXXX:client] Auto close remain: 4s
http:     [XXXXX:client] Auto close remain: 3s
http:     [XXXXX:client] Auto close remain: 2s
http:     [XXXXX:client] Auto close remain: 1s
http:     [XXXXX:client] Auto close remain: 0s
info:     [XXXXX:client] Closing the page
Status Session:  autocloseCalled
Session name:  XXXXX
verbose:  [XXXXX:page] Page Closed
Status Session:  browserClose
Session name:  XXXXX
Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSessionImpl.send (/var/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:316:35)
    at ExecutionContext._ExecutionContext_evaluate (/var/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)
    at async ExecutionContext.evaluate (/var/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
```
My JS code which I using:
```
const wppconnect = require('@wppconnect-team/wppconnect');
var contactIds = [];
wppconnect.defaultLogger.level = 'silly';
wppconnect
  .create({
      session: '+919903669943',
      debug:true,
      statusFind: (statusSession, session) => {
          console.log('Status Session: ', statusSession);
          console.log('Session name: ', session);
      },
      browserArgs: ['--no-sandbox'],
      autoClose: 60000
  })
  .then((client) => start(client))
  .catch((error) => console.log(error));

function start(client) {

}
```

**Comment by momokang** [comment]
I'm facing this error as well, I can't have a stable auto-reply whatsapp works :(

**Comment by edgardmessias** [comment]
Could you test with https://github.com/wppconnect-team/wppconnect/releases/tag/v1.19.1 ?

**Comment by rajenpal033** [comment]
@edgardmessias Yes it's working, I will still be checking further for few more times. But thank you very much.
