### ISSUE TITLE
n.loadEarlierMsgs is not a function => problems with loadAndGetAllMessagesInChat Method

### ISSUE THREAD

**Issue by IgorDePaula** [wppconnect-team/wppconnect#1501]
## Description

On use this method ```loadAndGetAllMessagesInChat``` I got the exception above in image.

## Environment

- **WPPConnect version(s):**1.2.0
- **WA-JS version(s):**  2.18.2
- **Browser:** Chrome XX / Chromium XX
- **OS:** ubuntu 22.04
- **Node version:** v16.14.2
- **WhatsApp version:** desktop
- **MultiDevice (BETA):** _( think that yes)_

## Steps to Reproduce
![Captura de tela de 2023-01-13 21-40-25](https://user-images.githubusercontent.com/2833993/212441868-0e3e85ea-5c96-48a4-a602-7a46ce793295.png)
The code is

## Log Output

```
Error: n.loadEarlierMsgs is not a function
    at /home/igor/projetos/wpp-bot/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:107:31
    at step (/home/igor/projetos/wpp-bot/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/home/igor/projetos/wpp-bot/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/home/igor/projetos/wpp-bot/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
JS Stack: TypeError: n.loadEarlierMsgs is not a function
    at Object.<anonymous> (/home/igor/projetos/wpp-bot/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:26997)
    at Generator.next (<anonymous>)
    at Q (/home/igor/projetos/wpp-bot/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:26462)
    at a (/home/igor/projetos/wpp-bot/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:26665)
    at W (https://web.whatsapp.com/bootstrap_qr.c8a228a8ac9e7fc0fc33.js:40:119522)
    at MutationObserver.x (https://web.whatsapp.com/bootstrap_qr.c8a228a8ac9e7fc0fc33.js:40:116099)
```

## Your Code

```js
const wppconnect = require('@wppconnect-team/wppconnect');

wppconnect
    .create()
    .then((client) => start(client))
    .catch((error) => console.log(error));

const start = async client => {

  /*  client.sendText('55999999999999@c.us', '👋 Hello from wppconnect! kkkkkkkkkkkkkkkkkk').then((result) => {
        console.log('Result: ', result); //return object success
    })
        .catch((erro) => {
            console.error('Error when sending: ', erro); //return object error
        });*/
    console.log(await client.loadAndGetAllMessagesInChat('55999999999@c.us'))
    /*client.onMessage(async (message) => {
        await client.startTyping(message.from, 5000);

        const msg = `Sr. ${message.notifyName}, ja esta de noite e não queremos abrir agora`
        client.sendText(message.from, msg).then((result) => {
            console.log('Result: ', result); //return object success
        })
            .catch((erro) => {
                console.error('Error when sending: ', erro); //return object error
            });
    });*/
}
```

## Additional context / Screenshot

![Captura de tela de 2023-01-13 21-40-25](https://user-images.githubusercontent.com/2833993/212441868-0e3e85ea-5c96-48a4-a602-7a46ce793295.png)

**Comment by edgardmessias** [comment]
This method is deprecated, please, try to use getMessages: https://wppconnect.io/wppconnect/classes/Whatsapp.html#getMessages

**Comment by IgorDePaula** [comment]
@edgardmessias update docs, please.

**Comment by edgardmessias** [comment]
Yes, I need to update some docs, I have been working on WA-JS to fix some problems with latest version of whatsapp. Pull request are welcome.

Note: I'm from Brazil, join on our discord

**Comment by IgorDePaula** [comment]
Great, I'from Brazil too. I dont like discord. But I will mae pull requests. I'm a laravel developer, I planned make a laravel composer package for contribute with the project. I'm in telegram group project.
