### ISSUE TITLE
Phone Not Connected after a 40-60 seconds of loading

### ISSUE THREAD

**Issue by roysG** [wppconnect-team/wppconnect#1551]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **WPPConnect version(s):** Latest
- **WA-JS version(s):** Lastest
- **Browser:** Chrome 
- **OS:** Linux
- **Node version:** 16.19.0
- **WhatsApp version:** 
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. Loading the connection
2. After some time if it take a while.. there is error of Phone Not Connected

## Log Output
 LOADING_SCREEN 70%
 LOADING_SCREEN 73%
 LOADING_SCREEN 75%
Phone Not Connected

Just in case the whatsapp is on the screen in the device it works..

Is there any way to increase the timeout until we see the message "Phone Not Connected" ??
```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by roysG** [comment]
Thanks!

**Comment by roysG** [comment]
I update to latest version. and now i get this error:

 LOADING_SCREEN 0 WhatsApp
714|5d73b9bf51f9648f44fb500b6e84ba91  | leftSecondFromStoppedLoop 0.108
714|5d73b9bf51f9648f44fb500b6e84ba91  | verbose:  [5d73b9bf51f9648f44fb500b6e84ba91:page] Page loaded
714|5d73b9bf51f9648f44fb500b6e84ba91  | verbose:  [5d73b9bf51f9648f44fb500b6e84ba91:client] Injecting wapi.js
714|5d73b9bf51f9648f44fb500b6e84ba91  | Error: Evaluation failed: ReferenceError: WPP is not defined
714|5d73b9bf51f9648f44fb500b6e84ba91  |     at pptr://__puppeteer_evaluation_script__:1:16
714|5d73b9bf51f9648f44fb500b6e84ba91  |     at ExecutionContext._ExecutionContext_evaluate (/root/msgto/server/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:255:15)
714|5d73b9bf51f9648f44fb500b6e84ba91  |     at runMicrotasks (<anonymous>)
714|5d73b9bf51f9648f44fb500b6e84ba91  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
714|5d73b9bf51f9648f44fb500b6e84ba91  |     at async ExecutionContext.evaluate (/root/msgto/server/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:143:16)
714|5d73b9bf51f9648f44fb500b6e84ba91  | (SIGINT) Shutting down...
714|5d73b9bf51f9648f44fb500b6e84ba91  | env prod serverId undefined
714|5d73b9bf51f9648f44fb500b6e84ba91  | whatsappWebApi.serverId 5d73b9bf51f9648f44fb500b6e84ba91
