### ISSUE TITLE
puppeteer

### ISSUE THREAD

**Issue by megustalol** [wppconnect-team/wppconnect#1725]
## Description

Quando instalo pela primeira vez a lib usando a versão mais atual do wppconnect da um erro de puppeteer e mesmo instalando manualmente com o npm i puppeteer o erro continua. Para resolver eu instalei a versão 1.23.0 ai instalou o google choromium e o puppeteer.
após instalar a 1.23.0 atualizei para a 1.27.2 e funcionou perfeitamente

## Environment

- **WPPConnect version(s):** 1.27.2
- **MultiDevice (BETA):** yes

## Log Output

    Note: puppeteer is a peer dependency of puppeteer-extra,
    which means you can install your own preferred version.

    - To get the latest stable version run: 'yarn add puppeteer' or 'npm i puppeteer'

    Alternatively:
    - To get puppeteer without the bundled Chromium browser install 'puppeteer-core'

error:    [bot:browser] Error no open browser
error:    [bot:browser] Unexpected token '??='
/root/bot/node_modules/puppeteer-core/lib/cjs/puppeteer/common/util.js:403
            callPuppeteer.args ??= new Map();
                               ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/root/bot/node_modules/puppeteer-core/lib/cjs/puppeteer/common/HTTPRequest.js:18:19)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)

**Comment by icleitoncosta** [comment]
Olá, por favor, usa o yarn install na instalação caso persista. Vamos atualizar as dependencias.
