### ISSUE TITLE
ProtocolError: Runtime.callFunctionOn timed

### ISSUE THREAD

**Issue by CebolinhaWiz** [wppconnect-team/wppconnect#1777]
# erro

Minha instância está caindo ao fazer envio de mensagens em massa.

# Minha hospedagem
1 GB RAM
0.5 vCPU
SSD NVMe Empresarial
Banda Ilimitada

## Log Output

```
[39m:    [BOT:client] Emitting onAnyMessage event (2 registered)
L[34mdebug[39m:    [BOT:client] Emitting onAnyMessage event (2 registered)
�[31merror[39m:    [BOT:client] ProtocolError: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
�[31merror[39m:    Unhandled Rejection: ProtocolError: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
|    at <instance_members_initializer> (/home/node/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:49:14)
j    at new Callback (/home/node/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:53:16)
u    at CallbackRegistry.create (/home/node/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:93:26)
r    at Connection._rawSend (/home/node/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:207:26)
r    at CDPSessionImpl.send (/home/node/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:416:33)
n    at #evaluate (/home/node/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:234:50)
R    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
�    at async ExecutionContext.evaluate (/home/node/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:149:16)
�[31merror[39m:    Unhandled Rejection: ProtocolError: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
|    at <instance_members_initializer> (/home/node/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:49:14)
j    at new Callback (/home/node/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:53:16)
u    at CallbackRegistry.create (/home/node/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:93:26)
r    at Connection._rawSend (/home/node/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:207:26)
r    at CDPSessionImpl.send (/home/node/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:416:33)
n    at #evaluate (/home/node/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:234:50)
�    at async ExecutionContext.evaluate (/home/node/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:149:16)
```

**Comment by Frankillin** [comment]
Encontrou alguma solução, estou com o mesmo problema.

**Comment by CebolinhaWiz** [comment]
> Encontrei alguma solução, estou com o mesmo problema.

Sim, aumentei a memória da minha hospedagem

**Comment by Saifallak** [comment]
+1

**Comment by icleitoncosta** [comment]
> > Encontrei alguma solução, estou com o mesmo problema.
> 
> Sim, aumentei a memória da minha hospedagem

Fechando a issue devido a solução postada aqui.

@Saifallak Try increasing your machine's memory; this will resolve the issue.
