### ISSUE TITLE
openChat returns Promise Error

### ISSUE THREAD

**Issue by VirusEcks** [wppconnect-team/wppconnect#1787]
## Description

when using `openChat` it will return a promise error after a while 

## Environment

- **WPPConnect version(s):** 1.28.0
- **WA-JS version(s):** 2.24.8
- **Browser:** Google Chrome 116.0.5845.96
- **OS:** debian 12
- **Node version:** Node 20.5.0
- **WhatsApp version:** 2.2331.9
- **MultiDevice (BETA):** yes

## Steps to Reproduce

```
handle_log('Searching for Chat: ' + message.chat.id);

bot.getChatById(message.chat.id).then((chat: whatsapp.Chat) => {

        handle_log('Found Chat: ' + chat.id._serialized);

           bot.openChat(message.chat.id).then((result: any) => {
                handle_log('Opened Chat: ' + chat.id._serialized);
           });
});

```

## Log Output

```
Searching for Chat: 'xxx@c.us'
Found Chat: 'xxx@c.us'

ProtocolError: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
at Callback.<instance_members_initializer> (/var/connect/whatsapp/node_modules/puppeteer-core/src/common/Connection.ts:66:12)
at new Callback (/var/connect/whatsapp/node_modules/puppeteer-core/src/common/Connection.ts:71:3)
at CallbackRegistry.create (/var/connect/whatsapp/node_modules/puppeteer-core/src/common/Connection.ts:127:22)
at Connection._rawSend (/var/connect/whatsapp/node_modules/puppeteer-core/src/common/Connection.ts:278:22)
at CDPSessionImpl.send (/var/connect/whatsapp/node_modules/puppeteer-core/src/common/Connection.ts:562:29)
at ExecutionContext.#evaluate (/var/connect/whatsapp/node_modules/puppeteer-core/src/common/ExecutionContext.ts:317:44)
at ExecutionContext.evaluate (/var/connect/whatsapp/node_modules/puppeteer-core/src/common/ExecutionContext.ts:192:12)
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by icleitoncosta** [comment]
Please, update for the latest version of wa-js and wppconnect.
