### ISSUE TITLE
Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

### ISSUE THREAD

**Issue by caiodutra08** [wppconnect-team/wppconnect#1924]
## Description

Não sei quando o erro acontece pois ele apenas acontece do nada sem motivo nenhum. Ele está funcionando normalmente e do nada para alguns usuários ele apenas para de mandar mensagem e ocorre esse erro:

InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

## Environment

- **WPPConnect version(s):** @WPPConnect/server 2.2.4,
- **WA-JS version(s):** @WPPConnect-team/wppconnect:  ^1.28.0,
- **MongoDB:** (Versão: 4.2.1)
- **Node version:** Node 18
- **MultiDevice (BETA):** Sim
- **VM GCP:** 32GB RAM 

## Log Output

```
InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
```

## Additional context / Screenshot

Minha hipótese é, que quando houver muitos dispositivos conectados, nosso servidor acaba sofrendo um outraging.

**Comment by Divino67** [comment]
same here

**Comment by RAKESHSUVIDYA** [comment]
error:    Unhandled Rejection: ProtocolError: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
    at <instance_members_initializer> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:96:14)
    at new Callback (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:100:16)
    at CallbackRegistry.create (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:32:26)
    at Connection._rawSend (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:91:26)
    at CdpCDPSession.send (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:78:33)
    at #evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:211:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:126:16)
    at async IsolatedWorld.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:128:16)
    at async CdpFrame.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:370:20)

**Comment by RAKESHSUVIDYA** [comment]
same here

**Comment by icleitoncosta** [comment]
Please increase the resources of the server where the project is running (memory and processing).
