### ISSUE TITLE
Protocol error (Runtime.callFunctionOn): Target closed send file over ~75mb

### ISSUE THREAD

**Issue by gleberson-alves** [wppconnect-team/wppconnect#1954]
## Description

I receive an error when sending a file larger than 75mb
When sending files close to and above 75mb I receive an error

## Environment

- **WPPConnect version(s):** 1.28.3
- **Browser:** Chrome 119.0.6045.159
- **OS:** Rocklinux 9.2
- **Node version:** Node v20.9.0
- **MultiDevice (BETA):** yes

## Log Output
TargetCloseError: Protocol error (Runtime.callFunctionOn): Target closed
    at CallbackRegistry.clear (/home/admin/robozap/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:103:30)
    at CdpCDPSession._onClosed (/home/admin/robozap/node_modules/puppeteer-core/src/cdp/CDPSession.ts:158:21)
    at Connection.#onClose (/home/admin/robozap/node_modules/puppeteer-core/src/cdp/Connection.ts:214:6)
    at WebSocket.<anonymous> (/home/admin/robozap/node_modules/puppeteer-core/src/node/NodeWebSocketTransport.ts:60:22)
    at callListener (/home/admin/robozap/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/home/admin/robozap/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:220:9)
    at WebSocket.emit (node:events:514:28)
    at WebSocket.emitClose (/home/admin/robozap/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:260:10)
    at Receiver.receiverOnFinish (/home/admin/robozap/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:1181:20)
    at Receiver.emit (node:events:514:28) {
  cause: ProtocolError: 
      at Callback.<instance_members_initializer> (/home/admin/robozap/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:114:12)
      at new Callback (/home/admin/robozap/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:119:3)
      at CallbackRegistry.create (/home/admin/robozap/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:37:22)
      at Connection._rawSend (/home/admin/robozap/node_modules/puppeteer-core/src/cdp/Connection.ts:129:13)
      at CdpCDPSession.send (/home/admin/robozap/node_modules/puppeteer-core/src/cdp/CDPSession.ts:105:29)
      at ExecutionContext.#evaluate (/home/admin/robozap/node_modules/puppeteer-core/src/cdp/ExecutionContext.ts:293:44)
      at ExecutionContext.evaluate (/home/admin/robozap/node_modules/puppeteer-core/src/cdp/ExecutionContext.ts:168:12)
      at IsolatedWorld.evaluate (/home/admin/robozap/node_modules/puppeteer-core/src/cdp/IsolatedWorld.ts:151:12)
      at CdpFrame.evaluate (/home/admin/robozap/node_modules/puppeteer-core/src/api/Frame.ts:516:6)
      at CdpPage.evaluate (/home/admin/robozap/node_modules/puppeteer-core/src/api/Page.ts:2221:3)
}

**Comment by gleberson-alves** [comment]
any solution?

**Comment by a1ex33** [comment]
estou com o mesmo problema

**Comment by icleitoncosta** [comment]
Please, try:
https://github.com/wppconnect-team/wppconnect/pull/2091
