### ISSUE TITLE
WhatsApp is out of date

### ISSUE THREAD

**Issue by momokang** [wppconnect-team/wppconnect#2040]
## Description

WhatsApp is out of date, I had run `npm update @wppconnect-team/wppconnect` but still having this issue, need help. My project is having issue now.

In wppconnect it shows update to date:
info:     Checking for updates
info:     You're up to date

## Log Output
verbose:  [session2:page] Page loaded
verbose:  [session2:client] Injecting wapi.js
verbose:  [session2:page] Page loaded
verbose:  [session2:client] Injecting wapi.js
verbose:  [session2:page] Page loaded
verbose:  [session2:client] Injecting wapi.js
ProtocolError: Protocol error (DOM.resolveNode): Node with given id does not belong to the document
    at C:\xampp\htdocs\whatsappbroadcast\node\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:329:24
    at new Promise (<anonymous>)
    at CDPSessionImpl.send (C:\xampp\htdocs\whatsappbroadcast\node\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:325:16)
    at IsolatedWorld.adoptBackendNode (C:\xampp\htdocs\whatsappbroadcast\node\node_modules\puppeteer-core\lib\cjs\puppeteer\common\IsolatedWorld.js:370:121)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async IsolatedWorld.adoptHandle (C:\xampp\htdocs\whatsappbroadcast\node\node_modules\puppeteer-core\lib\cjs\puppeteer\common\IsolatedWorld.js:382:17)
    at async IsolatedWorld.transferHandle (C:\xampp\htdocs\whatsappbroadcast\node\node_modules\puppeteer-core\lib\cjs\puppeteer\common\IsolatedWorld.js:385:24) {
  originalMessage: 'Node with given id does not belong to the document'
}
verbose:  [session2:client] wapi.js failed
verbose:  [session2:page] Page loaded
verbose:  [session2:client] Injecting wapi.js
verbose:  [session2:page] Page loaded
verbose:  [session2:client] Injecting wapi.js

**Comment by Sau64** [comment]
I solve this issue deleting inside node_modules/wa-version/ the htmls that became deprecated (oldest version)

**Comment by momokang** [comment]
Thank you @Sau64 , you are my life saver
