### ISSUE TITLE
Não envia arquivos maiores que 60MB

### ISSUE THREAD

**Issue by daniloricalmeida** [wppconnect-team/wppconnect#2064]
Ao tentar enviar um arquivo (ex: 70NM ou 90MB) o puppeteer crasha

## Environment

- **WPPConnect version(s):** 1.29.0
- **WA-JS version(s):**  2.28.1
- **Browser:** Chrome lastest
- **OS:** Debian 11
- **Node version:** Node 20.10.0
- **WhatsApp version:** 2.2404.x
- **MultiDevice (BETA):** yes

## Steps to Reproduce

Enviar um arquivo em torno de 70MB

## Log Output

```
ProtocolError: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
    at <instance_members_initializer> (/home/whats_api/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:96:14)
    at new Callback (/home/whats_api/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:100:16)
    at CallbackRegistry.create (/home/whats_api/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:22:26)
    at Connection._rawSend (/home/whats_api/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:80:26)
    at CdpCDPSession.send (/home/whats_api/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:66:33)
    at #evaluate (/home/whats_api/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:202:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/home/whats_api/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:117:16)
    at async IsolatedWorld.evaluate (/home/whats_api/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:124:16)
    at async CdpFrame.evaluate (/home/whats_api/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:347:20)
```

**Comment by icleitoncosta** [comment]
Fechando, e vamos discutir na PR #1954
