### ISSUE TITLE
Error Cannot read properties of undefined (reading 'm')

### ISSUE THREAD

**Issue by vitorvk2** [wppconnect-team/wppconnect#2173]
## Description

Depois que é feito a leitura do QR Code ocorre a injeção dupla do **Injecting wapi.js** sem nenhum motivo aparente, esse problema vem nativamente do Plugin.

## Environment

- **WPPConnect version(s):**  1.30.3
- **WA-JS version(s):** 3.2.5
- **Node version:** 20.13.1
- **WhatsApp version:** 2.3000.1013384762-alpha
- **MultiDevice (BETA):** no

## Steps to Reproduce

1. Realize leitura do QRCode
2. Perceba que será gerado de maneira dupla o Injecting wapi.js;
3. Nenhuma função irá funcionar porque sempre gerará o erro de Cannot read properties of undefined (reading 'm')

## Log Output

```
http:     [vitor-1:client] Checking QRCode status...
http:     [vitor-1:client] Login with success
Status Session:  qrReadSuccess
Session name:  vitor-1
debug:    [vitor-1:client] Emitting onInterfaceChange event (1 registered)
http:     [vitor-1:client] Current state: SYNCING (CONNECTING)
debug:    [vitor-1:client] Emitting onInterfaceChange event (1 registered)
http:     [vitor-1:client] Current state: SYNCING (CONNECTING)
info:     [vitor-1:client] Auto close configured to 180s
http:     [vitor-1:client] Checking phone is connected...
debug:    [vitor-1:client] Emitting onInterfaceChange event (1 registered)
http:     [vitor-1:client] Current state: SYNCING (CONNECTING)
debug:    [vitor-1:client] Emitting onInterfaceChange event (1 registered)
http:     [vitor-1:client] Current state: SYNCING (CONNECTING)
debug:    [vitor-1:client] Registering onStateChange event
new client:  vitor-1 Whatsapp {
  page: CdpPage { _isDragging: false, _timeoutSettings: TimeoutSettings {} },
  autoCloseInterval: null,
  autoCloseCalled: false,
  isInitialized: true,
  isInjected: true,
  isStarted: true,
  isLogged: true,
  isInChat: true,
  checkStartInterval: Timeout {
    _idleTimeout: 5000,
    _idlePrev: [Timeout],
    _idleNext: [Timeout],
    _idleStart: 42133,
    _onTimeout: [Function (anonymous)],
    _timerArgs: undefined,
    _repeat: 5000,
    _destroyed: false,
    [Symbol(refed)]: true,
    [Symbol(kHasPrimitive)]: false,
    [Symbol(asyncId)]: 616,
    [Symbol(triggerId)]: 0
  },
  urlCode: '2@ry6yAsFWbC0zjONEbUHg8bnYDebVECr+x6Ujht5Dk9ubJ2Es866YkhnNx8d1C6XhGWfJEZg4M5hPQw==,caTOlluq99fHOPgCzKeO0IqA24TOqJ42zfHeJxfdzgQ=,LTvQhhF9Hz1fIg1Wa2onkKH2aDT3ooC7zG1h2/+rPCM=,349qIOwyPzDOfFRbNQSklDVTnqaVXHUxPevKfmZrhFI=,1',
  attempt: 1,
  catchQR: [AsyncFunction: catchQR],
  statusFind: [AsyncFunction: statusFind],
  onLoadingScreen: undefined,
  catchLinkCode: undefined,
  session: 'vitor-1',
  options: {
    folderNameToken: '/tokens/',
    headless: true,
    devtools: false,
    useChrome: false,
    debug: false,
    logQR: false,
    browserWS: '',
    browserArgs: [ '' ],
    puppeteerOptions: { userDataDir: '/tokens/vitor-1', args: [Array] },
    disableWelcome: false,
    updatesLog: false,
    autoClose: 600000,
    deviceSyncTimeout: 180000,
    createPathFileToken: true,
    waitForLogin: true,
    logger: DerivedLogger {
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: true,
      allowHalfOpen: true,
      _transformState: [Object],
      silent: undefined,
      format: [Format],
      defaultMeta: null,
      levels: [Object],
      level: 'silly',
      exceptions: [ExceptionHandler],
      rejections: [RejectionHandler],
      profilers: {},
      exitOnError: true,
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false
    },
    tokenStore: 'file',
    whatsappVersion: '2.3000.1013384762-alpha',
    deviceName: false,
    linkPreviewApiServers: null,
    disableGoogleAnalytics: true,
    googleAnalyticsId: null,
    poweredBy: 'WPPConnect',
    session: 'vitor-1',
    catchQR: [AsyncFunction: catchQR],
    statusFind: [AsyncFunction: statusFind],
    disableSpins: true,
    sessionToken: undefined
  },
  logger: <ref *1> DerivedLogger {
    _readableState: ReadableState {
      objectMode: true,
      highWaterMark: 16,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [Console],
      pipesCount: 1,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: false,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      paused: false,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: true,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] {
      prefinish: [Function: prefinish],
      end: [Function],
      data: [Function: ondata]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: true,
      highWaterMark: 16,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function (anonymous)],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [CorkedRequest]
    },
    writable: true,
    allowHalfOpen: true,
    _transformState: {
      afterTransform: [Function: bound afterTransform],
      needTransform: true,
      transforming: false,
      writecb: null,
      writechunk: null,
      writeencoding: 'utf8'
    },
    silent: undefined,
    format: Format { options: {}, Format: [Function: Format] },
    defaultMeta: null,
    levels: {
      error: 0,
      warn: 1,
      info: 2,
      http: 3,
      verbose: 4,
      debug: 5,
      silly: 6
    },
    level: 'silly',
    exceptions: ExceptionHandler { logger: [Circular *1], handlers: Map(0) {} },
    rejections: RejectionHandler { logger: [Circular *1], handlers: Map(0) {} },
    profilers: {},
    exitOnError: true,
    [Symbol(shapeMode)]: true,
    [Symbol(kCapture)]: false
  },
  listenerEmitter: EventEmitter {
    _events: [Object: null prototype] {
      onInterfaceChange: [Function (anonymous)],
      onStateChange: [Function (anonymous)]
    },
    _eventsCount: 2,
    _maxListeners: 0,
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: true,
    [Symbol(nodejs.rejection)]: [Function (anonymous)]
  },
  connected: true
}
debug:    [vitor-1:client] Registering onAnyMessage event
debug:    [vitor-1:client] Registering onAck event
debug:    [vitor-1:client] Registering onRevokedMessage event
debug:    [vitor-1:client] Registering onReactionMessage event
debug:    [vitor-1:client] Emitting onInterfaceChange event (1 registered)
http:     [vitor-1:client] Current state: MAIN (NORMAL)
debug:    [vitor-1:client] Emitting onInterfaceChange event (1 registered)
http:     [vitor-1:client] Current state: MAIN (NORMAL)
debug:    [vitor-1:client] Emitting onInterfaceChange event (1 registered)
http:     [vitor-1:client] Current state: MAIN (NORMAL)
http:     [vitor-1:client] Connected
Status Session:  inChat
Session name:  vitor-1
verbose:  [vitor-1:page] Page loaded
verbose:  [vitor-1:client] Injecting wapi.js
verbose:  [vitor-1:page] Page loaded
verbose:  [vitor-1:client] Injecting wapi.js
DEU ERRO - getAllMessagesInChat Error: Cannot read properties of undefined (reading 'm')
    at /usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:107:31
    at step (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
JS Stack: TypeError: Cannot read properties of undefined (reading 'm')
    at Object.p [as searchId] (/usr/src/app/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:309107)
    at Object.get [as WidFactory] (/usr/src/app/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:326423)
    at t.createWid (/usr/src/app/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:298603)
    at t.assertWid (/usr/src/app/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:101819)
    at t.get (/usr/src/app/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:142062)
    at t.assertGetChat (/usr/src/app/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:100183)
    at t.getMessages (/usr/src/app/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:144645)
    at Object.e (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:41680)
    at e.next (<anonymous>)
    at be (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:41476)
    at a (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:42011)
    at /usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:42072
    at new Promise (<anonymous>)
    at Object.We (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:41951)
    at Object.We (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:42089)
    at window.WAPI.window.WAPI.getMessages (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:71385)
    at pptr:evaluate;%2Fusr%2Fsrc%2Fapp%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:58:41
    at pptr:evaluate;%2Fusr%2Fsrc%2Fapp%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:59:28
    at new Promise (<anonymous>)
    at anonymous (pptr:evaluate;%2Fusr%2Fsrc%2Fapp%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:54:14)
```

## Your Code

```
const create = async (
  sessionName,
  webhookUrl,
  tenancyName,
  anyMessageQueueName,
  anyAckQueueName
) => {
  return new Promise(async (resolve, reject) => {
    const response = {
      qrCode: null,
      statusSession: null,
      session: null
    }
    let qrCode = '';

    const cachedQrCode = await findQrCodeSessionFromCache(sessionName);
    if (cachedQrCode !== false) {
      return resolve({
        qrCode: cachedQrCode.base64Qr,
        session: cachedQrCode.sessionName
      });
    }

    wppconnect.create({
      session: sessionName,
      catchQR: async (base64Qr, asciiQR, attempts) => {
        try {
          response.qrCode = base64Qr;
          console.log(asciiQR);
          if (attempts === 1) {
            resolve(response);
          }

          await removeQrCodeFromCache(sessionName);

          cache.get('qrCodes', function (err, QrCodes) {
            const parsedQrCodes = (JSON.parse(QrCodes));
            parsedQrCodes.pushIfNotExist({
              sessionName,
              webhookUrl,
              base64Qr
            }, (event) => {
              return event.sessionName === sessionName
                && event.webhookUrl === webhookUrl
                && event.base64Qr === base64Qr;
            });

            cache.set('qrCodes', JSON.stringify(parsedQrCodes));
          });

          axios.post(webhookUrl, {
            base64Qr,
            event: 'qrCodeChanged',
            sessionName
          }, {httpsAgent: agent}).catch(error => {
            console.log('qrCodeChanged error: ', error);
          });
        } catch (error) {
          console.log(error);
        }
      },
      statusFind: async (statusSession, session) => {
        try {
          response.statusSession = statusSession;
          response.session = session;
          console.log('Status Session: ', statusSession);
          console.log('Session name: ', session);
          axios.post(webhookUrl, {
            statusSession,
            session,
            event: 'phoneStatus'
          }, {httpsAgent: agent}).catch(error => {
            console.log('phoneStatus error: ', error);
          });

          if (statusSession === 'serverClose') {
            await delay(15000);
            console.log(session)
            console.log(sessionClient[session])
            if (sessionClient[session] !== undefined) {
              create(
                sessionName,
                webhookUrl,
                tenancyName,
                anyMessageQueueName,
                anyAckQueueName
              );
            }
          }

          if (statusSession === 'qrReadFail' || statusSession === 'autocloseCalled') {
            removeSessionFromCache(session);
            delete sessionClient[session];
          }

          if (
            statusSession === 'qrReadFail' ||
            statusSession === 'isLogged' ||
            statusSession === 'serverClose' ||
            statusSession === 'inChat' ||
            statusSession === 'browserClose' ||
            statusSession === 'qrReadSuccess' ||
            statusSession === 'autocloseCalled'
          ) {
            removeQrCodeFromCache(session);
          }
        } catch (error) {
          console.log(error);
        }
      },
      headless: true,
      devtools: false,
      useChrome: false,
      debug: false,
      logQR: false,
      folderNameToken: process.env.TOKENS_PATH,
      puppeteerOptions: {
        userDataDir: process.env.TOKENS_PATH + sessionName,
        args: [
          '--log-level=3',
          '--no-default-browser-check',
          '--disable-site-isolation-trials',
          '--no-experiments',
          '--ignore-gpu-blacklist',
          '--ignore-certificate-errors',
          '--ignore-certificate-errors-spki-list',
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--disable-gpu',
          '--disable-extensions',
          '--disable-default-apps',
          '--enable-features=NetworkService',
          '--disable-setuid-sandbox',
          '--disable-dev-shm-usage',
          '--no-first-run'
        ]
      },
      disableSpins: true,
      disableWelcome: false,
      updatesLog: false,
      autoClose: 600000,
      whatsappVersion: '2.3000.1013384762-alpha'
    }).then((client) => {
      console.log('new client: ', sessionName, client);

      try {
        start(
          client,
          webhookUrl,
          sessionName,
          tenancyName,
          anyMessageQueueName,
          anyAckQueueName
        );
        sessionClient[sessionName] = client;

        cache.get('sessions', function (err, sessions) {
          const parsedSessions = (JSON.parse(sessions));
          parsedSessions.pushIfNotExist({
            sessionName,
            webhookUrl,
            tenancyName,
            anyMessageQueueName,
            anyAckQueueName
          }, (event) => {
            return event.sessionName === sessionName
              && event.webhookUrl === webhookUrl;
          });

          cache.set('sessions', JSON.stringify(parsedSessions));
        });

        resolve(response);
      } catch (error) {
        reject(error);
      }
    }).catch((error) => {
      if (error.message && error.message.includes('Failed to launch the browser process')) {
        cleanTokensFolder(true);
      }
      reject(error);
    });
  });
};
```

**Comment by icleitoncosta** [comment]
Olá vitor, durante a sincronização evite chamar funções. Só chame apenas se o isAuthenticated estiver como true.

**Comment by Saifallak** [comment]
i made a delay before calling any function on that session 2-4 mins, that's not ideal, I there any idea how to just reject call from `wppconnnect` if it's not ready yet?, because session is fully corrupted after that, and needs to be restarted to get it work
