### ISSUE TITLE
error contactStatus Error 

### ISSUE THREAD

**Issue by antirek** [wppconnect-team/wppconnect#2179]
## Description

try getStatus - receive error

`````
error contactStatus Error: o.StatusStore.find is not a function
     at /usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:107:31
     at step (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
     at Object.next (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
     at fulfilled (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
 JS Stack: TypeError: o.StatusStore.find is not a function
     at t.getStatus (/usr/src/app/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:225807)
 Function: function (contactId) { return __awaiter(_this, void 0, void 0, function () {
                             var status;
                             return __generator(this, function (_a) {
                                 switch (_a.label) {
                                     case 0: return [4 /*yield*/, WPP.contact.getStatus(contactId)];
                                     case 1:
                                         status = _a.sent();
                                         return [2 /*return*/, {
                                                 id: contactId,
                                                 status: (status === null || status === void 0 ? void 0 : status.status) || status,
                                             }];
                                 }
                             });
                         }); }

`````

## Environment

- **WPPConnect version(s):** 1.30.3
- **WA-JS version(s):** 3.2.6
- **Browser:** Chrome 124
- **OS:** Ubuntu 20.04
- **Node version:** Node 20
- **WhatsApp version:** 2.3000.1013384762-alpha
- **MultiDevice (BETA):** yes

**Comment by icleitoncosta** [comment]
Hello, this was a temporary error caused by a change in WhatsApp. Please update wa-js.
`npm install @wppconnect/wa-js@latest`
