### ISSUE TITLE
Number doesn't exists

### ISSUE THREAD

**Issue by fredzolio** [wppconnect-team/wppconnect#2208]
Estou tendo problemas relacionado a "Numero não existe"

No log obtenho:
`info: 2024-06-11T12:08:30.285Z ID: 8P0azz4B0iyuPIhJAAAJ entrou
Error: Cannot read properties of undefined (reading 'm')
    at /usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:107:31
    at step (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
JS Stack: TypeError: Cannot read properties of undefined (reading 'm')
    at Object.p [as searchId] (/usr/src/wpp-server/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:310618)
    at Object.get [as WidFactory] (/usr/src/wpp-server/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:327934)
    at t.createWid (/usr/src/wpp-server/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:300114)
    at t.assertWid (/usr/src/wpp-server/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:102100)
    at t.queryExists (/usr/src/wpp-server/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:228460)
    at pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:75
    at pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:102
    at new Promise (<anonymous>)
    at anonymous (pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:54:14)
Function: function (contactId) { return WPP.contact.queryExists(contactId); }`

**Comment by gekkedev** [comment]
Any code for reproduction?

**Comment by ijro** [comment]
I received this exact error as soon as I first connected a second phone number. 
The group list also did not appear.
Restarting the service solved it for me.
If you use pm2 for management it would be:

pm2 reload <container name>

**Comment by fereinaux** [comment]
same here, it was working until last week

**Comment by icleitoncosta** [comment]
Please, test: https://github.com/wppconnect-team/wppconnect/tree/wapi2

**Comment by icleitoncosta** [comment]
Fixed by https://github.com/wppconnect-team/wppconnect/commit/2962aac57b110e8951140e4873a7485f47714816
