### ISSUE TITLE
Failed to launch the browser process! undefined

### ISSUE THREAD

**Issue by mszpr** [wppconnect-team/wppconnect#2259]
## Description

Hi there!,
When i want to run multi instances on wppconnect this message appeared to me:

info:     [10000000004:browser] Using browser folder '/Users/mahmoud/Desktop/Projects/whatsapp/wa-instance-wppconnect/tokens/10000000004'
info:     [10000000004:browser] Initializing browser...
error:    [10000000003:browser] Error no open browser
error:    [10000000003:browser] Failed to launch the browser process! undefined
[98249:259:0712/030811.557031:ERROR:process_singleton_posix.cc(335)] Failed to create /Users/mahmoud/Desktop/Projects/whatsapp/wa-instance-wppconnect/tokens/10000000003/SingletonLock: File exists (17)
[98249:259:0712/030811.557323:ERROR:chrome_main_delegate.cc(592)] Failed to create a ProcessSingleton for your profile directory. This means that running multiple instances would start multiple browser processes rather than opening a new window in the existing process. Aborting now to avoid profile corruption.

TROUBLESHOOTING: https://pptr.dev/troubleshooting

## Environment

- **WPPConnect version(s):** 1.32.3
- **WA-JS version(s):** 3.2.4
- **Browser:** Chrome XX / Chromium XX
- **OS:** Macos, ubuntu 
- **Node version:** v20.8.0
- **WhatsApp version:** none
- **MultiDevice (BETA):** yes

## Log Output

```
error:    [10000000003:browser] Error no open browser
error:    [10000000003:browser] Failed to launch the browser process! undefined
[98249:259:0712/030811.557031:ERROR:process_singleton_posix.cc(335)] Failed to create /Users/mahmoud/Desktop/Projects/whatsapp/wa-instance-wppconnect/tokens/10000000003/SingletonLock: File exists (17)
[98249:259:0712/030811.557323:ERROR:chrome_main_delegate.cc(592)] Failed to create a ProcessSingleton for your profile directory. This means that running multiple instances would start multiple browser processes rather than opening a new window in the existing process. Aborting now to avoid profile corruption.


TROUBLESHOOTING: https://pptr.dev/troubleshooting

error:    Unhandled Rejection: Error: Failed to launch the browser process! undefined
[98249:259:0712/030811.557031:ERROR:process_singleton_posix.cc(335)] Failed to create /Users/mahmoud/Desktop/Projects/whatsapp/wa-instance-wppconnect/tokens/10000000003/SingletonLock: File exists (17)
[98249:259:0712/030811.557323:ERROR:chrome_main_delegate.cc(592)] Failed to create a ProcessSingleton for your profile directory. This means that running multiple instances would start multiple browser processes rather than opening a new window in the existing process. Aborting now to avoid profile corruption.


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (/Users/mahmoud/Desktop/Projects/whatsapp/wa-instance-wppconnect/node_modules/@puppeteer/browsers/lib/cjs/launch.js:310:24)
    at ChildProcess.emit (node:events:526:35)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```

## Your Code

`
const getDirectories = async source =>
  (await readdir(source, { withFileTypes: true }))
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name);

class Instance{

constructor(){
    this.restorePreviousSessions();
  }

createInstance(session_id){
 var options = {
        session: session_id,
        browserArgs: [
          '--disable-setuid-sandbox',
          '--no-sandbox',
          '--safebrowsing-disable-auto-update',
          '--disable-features=LeakyPeeker' // Disable the browser's sleep mode when idle, preventing the browser from going into sleep mode, this is useful for WhatsApp not to be in economy mode in the background, avoiding possible crashes
        ],
        puppeteerOptions: {
            userDataDir: `${__dirname}/tokens/${session_id}`,
            args: ['--no-sandbox','--disable-setuid-sandbox'],
            executablePath: process.env.ENV == 'local' ? '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' : '/usr/bin/google-chrome',
        },
        disableWelcome:true,
        headless:true,
        onLoadingScreen: (percent, message) => { onLoadingScreen (percent, message)},
        catchQR: (base64Qr, asciiQR, attempt, urlCode) => { onQrCode(base64Qr, asciiQR, attempt, urlCode) },
        statusFind: (statusFind) => { onStatus(statusFind) },
        catchLinkCode: (code) => { onLoginCode(code) },
        logQR:false,
      }

 client = await wppconnect.create(options);
}
}

  async restorePreviousSessions() {

    const directoryNames = await getDirectories(
      __dirname+"/tokens"
    );

    const sessionIds = directoryNames.map(name => name);

    sessionIds.forEach((sessionId,index) => {

      setTimeout(() => {
        console.log(`initialize session id => ${sessionId}`);
        this.createInstance(sessionId);
      }, process.env.RUNTIMEOUT || 20000 * (index + 1));
      
    });
    
  }`

This issue happen when i restore all instances after restart supervisor using  restorePreviousSessions() method 

thanks in advance.

**Comment by mszpr** [comment]
i found the issue, 
the issue was when i close the node js by my self or by any exception , Google Chrome page not closing  and still working in background. 

so the solution was to set listener to listen if node about to close, close all pages then continue closing the node app.

exmaple:
`var softCloseAll = false;
process.stdin.resume();
[`exit`, `SIGINT`, `SIGUSR1`, `SIGUSR2`, `SIGTERM`].forEach((eventType) => {

  if(!softCloseAll){
    process.on(eventType, (e) => {
      softCloseAll = true;
      ws.softCloseAll().then(() => {
        console.log("All clients has been closed!");
          process.exit();
      });
    });
  }

});`

**Comment by Saifallak** [comment]
> i found the issue, the issue was when i close the node js by my self or by any exception , Google Chrome page not closing and still working in background.
> 
> so the solution was to set listener to listen if node about to close, close all pages then continue closing the node app.
> 
> exmaple:
> 
> ```
> var softCloseAll = false;
> process.stdin.resume();
> [`exit`, `SIGINT`, `SIGUSR1`, `SIGUSR2`, `SIGTERM`].forEach((eventType) => {
> 
>   if(!softCloseAll){
>     process.on(eventType, (e) => {
>       softCloseAll = true;
>       ws.softCloseAll().then(() => {
>         console.log("All clients has been closed!");
>           process.exit();
>       });
>     });
>   }
> 
> });
> ```

Getting the same even for new sessions ..

**Comment by huogerac** [comment]
I was running the wppconnect-server and had the issue related to this issue:
And because I already have one session that I didn't want to loose..

```
TROUBLESHOOTING: https://pptr.dev/troubleshooting
 - Error: Failed to launch the browser process! undefined
[24:24:0313/174031.899934:ERROR:process_singleton_posix.cc(353)] The profile appears to be in use by another Chromium process (24) on another computer (f23caf625ae9). Chromium has locked the profile so that it doesn't get corrupted. If you are sure no other processes are using this profile, you can unlock the profile and relaunch Chromium.
[24:24:0313/174031.900008:ERROR:message_box_dialog.cc(146)] Unable to show a dialog outside the UI thread message loop: Chromium - The profile appears to be in use by another Chromium process (24) on another computer (f23caf625ae9). Chromium has locked the profile so that it doesn't get corrupted. If you are sure no other processes are using this profile, you can unlock the profile and relaunch Chromium.


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (/usr/src/wpp-server/node_modules/@puppeteer/browsers/lib/cjs/launch.js:314:24)
    at ChildProcess.emit (node:events:531:35)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
^Ccontext canceled
```

The solution was to remove the locks files, so I removed over my UserDataDir folder the files:
```
rm -rf $(pwd)/wppconnect_userDataDir/mysessionname/SingletonLock
rm -rf $(pwd)/wppconnect_userDataDir/mysessionname//SingletonCookie
```
