### ISSUE TITLE
(0 , i.findChat) is not a function on client.sendFile() method

### ISSUE THREAD

**Issue by Divino67** [wppconnect-team/wppconnect#2268]
## Description

Whenever you send a message with a file, this error is returned by promise.

## Environment

- **WPPConnect version(s):** 1.32.3
- **WA-JS version(s):** 3.4.2
- **Browser:** Chrome 119.0.6045.199
- **OS:** Linux Ubuntu 22.04
- **Node version:** Node 18.19
- **WhatsApp version:** 2.2411.x

## Steps to Reproduce

1. [First Step]
Connect on whatsapp by wpp connect

2. [Second Step]
Use the method client.sendFile() to send a message to an already verified number that exists.

3. [and so on...]
I see the error happen and fall into the promise catch

## Log Output

this is error message:
(0 , i.findChat) is not a function

this is log error complete:
 Error: (0 , i.findChat) is not a function
     at /home/r2zap/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:107:31
     at step (/home/r2zap/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
     at Object.next (/home/r2zap/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
     at fulfilled (/home/r2zap/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
 JS Stack: TypeError: (0 , i.findChat) is not a function
     at t.find (/home/r2zap/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:141119)
     at t.assertFindChat (/home/r2zap/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:100122)
     at t.sendFileMessage (/home/r2zap/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:177250)
     at pptr:evaluate;%2Fhome%2Fr2zap%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:62:79
     at step (pptr:evaluate;%2Fhome%2Fr2zap%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:47:27)
     at Object.next (pptr:evaluate;%2Fhome%2Fr2zap%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:28:57)
     at pptr:evaluate;%2Fhome%2Fr2zap%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:22:75
     at new Promise (<anonymous>)
         at __awaiter (pptr:evaluate;%2Fhome%2Fr2zap%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:18:16)
         at pptr:evaluate;%2Fhome%2Fr2zap%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:56
         at pptr:evaluate;%2Fhome%2Fr2zap%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:74:36
         at new Promise (<anonymous>)
             at anonymous (pptr:evaluate;%2Fhome%2Fr2zap%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:54:14)
         Function: function (_a) { return __awaiter(_this, [_a], void 0, function (_b) {
                                             var result;
                                             var _c;
                                             var to = _b.to, base64 = _b.base64, options = _b.options;
                                             return __generator(this, function (_d) {
                                                 switch (_d.label) {
                                                     case 0: return [4 /*yield*/, WPP.chat.sendFileMessage(to, base64, options)];
                                                     case 1:
                                                         result = _d.sent();
                                                         _c = {
                                                             ack: result.ack,
                                                             id: result.id
                                                         };
                                                         return [4 /*yield*/, result.sendMsgResult];
                                                     case 2: return [2 /*return*/, (_c.sendMsgResult = _d.sent(),
                                                             _c)];
                                                 }
                                             });
                                         }); }

**Comment by surfjzo** [comment]
I'm with the same issue.
But with the whatsappVersion: '2.3000.1014610951-alpha' is working.

**Comment by eduardoxRib** [comment]
With .sendText is happening the same error

**Comment by icleitoncosta** [comment]
Please, update for the latest version.

Already fixed

**Comment by Edson2001** [comment]
> Please, update for the latest version.
> 
> Already fixed

It worked for me
