### ISSUE TITLE
error when send mp4 video file

### ISSUE THREAD

**Issue by antirek** [wppconnect-team/wppconnect#2347]
## Description

when try send mp4 video file size 2Mb via wppconnect - receive error

when send this file via standard web whatsapp interface - ok

`````javascript
error

{
   name: 'InvalidMediaCheckRepairFailedType',
   message: '{"name":"InvalidMediaCheckRepairFailedType","stack":"InvalidMediaCheckRepairFailedType\\n    at a.d [as constructor] (https://static.whatsapp.net/rsrc.php/v3i1FW4/yv/l/rt/_9wK9CvzQFY.js?_nc_x=Ij3Wp8lg5Kz:33:217)\\n    at new a (https://static.whatsapp.net/rsrc.php/v3i1FW4/yv/l/rt/_9wK9CvzQFY.js?_nc_x=Ij3Wp8lg5Kz:34:1016)\\n    at Object.<anonymous> (https://static.whatsapp.net/rsrc.php/v3i1FW4/yv/l/rt/_9wK9CvzQFY.js?_nc_x=Ij3Wp8lg5Kz:2576:6729)\\n    at Generator.next (<anonymous>)\\n    at h (https://static.whatsapp.net/rsrc.php/v3iTNN4/yZ/l/rt/lGXMNxeIh9MVXgil27PkiKaMMWwcn9VT9vsWqehdEtWw.js?_nc_x=Ij3Wp8lg5Kz:43:125)\\n    at g (https://static.whatsapp.net/rsrc.php/v3iTNN4/yZ/l/rt/lGXMNxeIh9MVXgil27PkiKaMMWwcn9VT9vsWqehdEtWw.js?_nc_x=Ij3Wp8lg5Kz:43:349)"}',
   err: InvalidMediaCheckRepairFailedType: {"name":"InvalidMediaCheckRepairFailedType","stack":"InvalidMediaCheckRepairFailedType\n    at a.d [as constructor] (https://static.whatsapp.net/rsrc.php/v3i1FW4/yv/l/rt/_9wK9CvzQFY.js?_nc_x=Ij3Wp8lg5Kz:33:217)\n    at new a (https://static.whatsapp.net/rsrc.php/v3i1FW4/yv/l/rt/_9wK9CvzQFY.js?_nc_x=Ij3Wp8lg5Kz:34:1016)\n    at Object.<anonymous> (https://static.whatsapp.net/rsrc.php/v3i1FW4/yv/l/rt/_9wK9CvzQFY.js?_nc_x=Ij3Wp8lg5Kz:2576:6729)\n    at Generator.next (<anonymous>)\n    at h (https://static.whatsapp.net/rsrc.php/v3iTNN4/yZ/l/rt/lGXMNxeIh9MVXgil27PkiKaMMWwcn9VT9vsWqehdEtWw.js?_nc_x=Ij3Wp8lg5Kz:43:125)\n    at g (https://static.whatsapp.net/rsrc.php/v3iTNN4/yZ/l/rt/lGXMNxeIh9MVXgil27PkiKaMMWwcn9VT9vsWqehdEtWw.js?_nc_x=Ij3Wp8lg5Kz:43:349)"}
       at /usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:107:31
       at step (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
       at Object.next (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
       at fulfilled (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
   JS Stack: InvalidMediaCheckRepairFailedType
       at a.d [as constructor] (https://static.whatsapp.net/rsrc.php/v3i1FW4/yv/l/rt/_9wK9CvzQFY.js?_nc_x=Ij3Wp8lg5Kz:33:217)
       at new a (https://static.whatsapp.net/rsrc.php/v3i1FW4/yv/l/rt/_9wK9CvzQFY.js?_nc_x=Ij3Wp8lg5Kz:34:1016)
       at Object.<anonymous> (https://static.whatsapp.net/rsrc.php/v3i1FW4/yv/l/rt/_9wK9CvzQFY.js?_nc_x=Ij3Wp8lg5Kz:2576:6729)
       at Generator.next (<anonymous>)
       at h (https://static.whatsapp.net/rsrc.php/v3iTNN4/yZ/l/rt/lGXMNxeIh9MVXgil27PkiKaMMWwcn9VT9vsWqehdEtWw.js?_nc_x=Ij3Wp8lg5Kz:43:125)
       at g (https://static.whatsapp.net/rsrc.php/v3iTNN4/yZ/l/rt/lGXMNxeIh9MVXgil27PkiKaMMWwcn9VT9vsWqehdEtWw.js?_nc_x=Ij3Wp8lg5Kz:43:349)
   Function: function (_a) { return __awaiter(_this, [_a], void 0, function (_b) {
                                   var result;
                                   var _c;
                                   var to = _b.to, base64 = _b.base64, options = _b.options;
                                   return __generator(this, function (_d) {
                                       switch (_d.label) {
                                           case 0: return [4 /*yield*/, WPP.chat.sendFileMessage(to, base64, options)];
                                           case 1:
                                               result = _d.sent();
                                               _c = {
                                                   ack: result.ack,
                                                   id: result.id
                                               };
                                               return [4 /*yield*/, result.sendMsgResult];
                                           case 2: return [2 /*return*/, (_c.sendMsgResult = _d.sent(),
                                                   _c)];
                                       }
                                   });
                               }); }
  }
`````

## Environment

- **WPPConnect version(s):** 1.34.1
- **WA-JS version(s):** 3.10.1
- **Browser:** Chrome 128
- **OS:** Ubuntu 20.04
- **Node version:** Node 20
- **WhatsApp version:** 2.3000.1016510599-alpha
-

**Comment by antirek** [comment]
its like #2124

**Comment by icleitoncosta** [comment]
Can you send me that video so I can test it? I ran some tests today, and I’m able to send both the mp4 file and the base64 format. It would also be helpful if you could include how you are calling the function here.

**Comment by ethan2cl** [comment]
i got the same question, i can provide video file

**Comment by antirek** [comment]
@icleitoncosta 
video here https://filesamples.com/samples/video/mp4/sample_960x540.mp4 
I send base64 format to sendFile

**Comment by icleitoncosta** [comment]
Can you update your whatsappVersion to 2.3000.1017390231 and test again, please?

**Comment by andradecaua** [comment]
Guys, this error is because the whatsapp don't support de video format, i tryied here with others video type and workly, but i tryied with two types of mp4 and 1 work and other not, and the same with don't work in wpp lib, don't work in whatsapp web

**Comment by antirek** [comment]
oh, I update wa-version & check yesterday - and all work ok. @icleitoncosta, thanks))
