### ISSUE TITLE
client.listChats return undefined

### ISSUE THREAD

**Issue by ethan2cl** [wppconnect-team/wppconnect#2395]
## Description

client.listChats return undefined， But in fact, I have many contacts

## Environment
- **WA-JS version(s):** 3.10.2

**Comment by ethan2cl** [comment]
Occasional, not common

**Comment by icleitoncosta** [comment]
Even if you are using count, like:
`client.listChats({count: 20})` ?

**Comment by ethan2cl** [comment]
just use like  await client.listChats(), But I asked two other friends to help scan the code, and calling it like this would work. However, one of my friends, no matter how long it takes to log in, calls this API and returns undefined. I'll try adding count

**Comment by ethan2cl** [comment]
my whatsapp version is 2.3000.1017381166-alpha

**Comment by ethan2cl** [comment]
got a new ERROR
`Error [ModelCreateError]: Unknown
    at evaluateAndReturn (/project/back/wpp_new/api/helpers/evaluate-and-return.js:89:15)
    at async Whatsapp.listChats (/project/back/wpp_new/api/layers/retriever.layer.js:65:16)
    at async syncAllChats (/project/back/wpp_new/server/producer/chat.js:23:23)
JS Stack: ModelCreateError: Unknown
    at a.d [as constructor] (https://static.whatsapp.net/rsrc.php/v3i7Ki4/y7/l/rt/tjVUnJcsFpg.js:32:217)
    at new a (https://static.whatsapp.net/rsrc.php/v3i7Ki4/y7/l/rt/tjVUnJcsFpg.js:33:4582)
    at e.<anonymous> (https://static.whatsapp.net/rsrc.php/v3i7Ki4/y7/l/rt/tjVUnJcsFpg.js:2590:5771)
    at Generator.next (<anonymous>)
    at h (https://static.whatsapp.net/rsrc.php/v3iTNN4/y9/l/rt/GxSTLZtzbLuVXgil27PkiK31rCZGXc8SY5RyqAsAOH9WvsWqehdEtWw.js:42:125)
    at g (https://static.whatsapp.net/rsrc.php/v3iTNN4/y9/l/rt/GxSTLZtzbLuVXgil27PkiK31rCZGXc8SY5RyqAsAOH9WvsWqehdEtWw.js:42:349)
Function: async ({ options }) => {
            const chats = await WPP.chat.list(options);
            const serialized = chats.map((c) => WAPI._serializeChatObj(c));
            return serialized;
        }[39m`

**Comment by icleitoncosta** [comment]
@ethan2cl Whats the version of wppconnect?

**Comment by icleitoncosta** [comment]
@ethan2cl before call function listChats, please check device is authenticated an syncronizate.
`client.isMainReady()`
