### ISSUE TITLE
Do not send files larger than +-60mb (Runtime.callFunctionOn timed out)

### ISSUE THREAD

**Issue by Divino67** [wppconnect-team/wppconnect#2413]
## Description

When I use the function client.sendFile(to, pathOrBase64, options?) to send a PDF file in base64, passing the "type" property as "document" in the options object, the file is not sent.

Before, I used the client.setLimit('maxFileSize',900857600) function to change the maximum file size to 900mb.

However, if I send a file larger than +-60mb, an error is returned and the file is not sent.

## Environment

- **WPPConnect version(s):** 1.35.1
- **WA-JS version(s):** 3.14.0
- **Browser:** Chrome 127.0.6533.119
- **OS:** Linux Ubuntu 24.04.5 LTS
- **Node version:** 18.20.4
- **WhatsApp version:** 2.3000.1017390231
- **MultiDevice (BETA):** no

## Error returned

```
ProtocolError: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
    at <instance_members_initializer> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:94:14)
    at new Callback (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:98:16)
    at CallbackRegistry.create (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:23:26)
    at Connection._rawSend (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:90:26)
    at CdpCDPSession.send (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:66:33)
    at #evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:363:50)
    at ExecutionContext.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:278:36)
    at IsolatedWorld.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:100:30)
    at CdpFrame.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:346:43)
    at CdpFrame.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:109:27)
```

## Code used to set the maximum file upload limit

`
client.setLimit('maxFileSize', 900857600);
`

## Code used to send the file

```
const file = 'data:application/pdf;base64,JVBERi0xLjMKMyAwIG9ia...'

await client.sendFile('xxxxxxxxxxxxx@c.us', file, {
            type: 'document',
            caption: '',
            filename: 'pdf_file.pdf'
            mimetype: 'application/pdf',
            markIsRead: false,
        }).then(resp => resp).catch(err => {
                console.log(err);
                throw err;
            });
```

**Comment by manfe** [comment]
Something related to this:

Also when trying to send large files over 20MB+

```sh
Protocol error (Runtime.callFunctionOn): Target closed
    err: {
      "type": "TargetCloseError",
      "message": "Protocol error (Runtime.callFunctionOn): Target closed: ",
      "stack":
          TargetCloseError: Protocol error (Runtime.callFunctionOn): Target closed
              at CallbackRegistry.clear (<base-path>/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:101:30)
              at CdpCDPSession.onClosed (<base-path>/node_modules/puppeteer-core/src/cdp/CdpSession.ts:162:21)
              at Connection.#onClose (<base-path>/node_modules/puppeteer-core/src/cdp/Connection.ts:226:15)
              at WebSocket.<anonymous> (<base-path>/node_modules/puppeteer-core/src/node/NodeWebSocketTransport.ts:51:22)
              at callListener (<base-path>/node_modules/ws/lib/event-target.js:290:14)
              at WebSocket.onClose (<base-path>/node_modules/ws/lib/event-target.js:220:9)
              at WebSocket.emit (node:events:519:28)
              at WebSocket.emitClose (<base-path>/node_modules/ws/lib/websocket.js:272:10)
              at Receiver.receiverOnFinish (<base-path>/node_modules/ws/lib/websocket.js:1209:20)
              at Receiver.emit (node:events:519:28)
          caused by: ProtocolError: 
              at Callback.<instance_members_initializer> (<base-path>/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:127:12)
              at new Callback (<base-path>/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:132:3)
              at CallbackRegistry.create (<base-path>/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:30:22)
              at Connection._rawSend (<base-path>/node_modules/puppeteer-core/src/cdp/Connection.ts:136:22)
              at CdpCDPSession.send (<base-path>/node_modules/puppeteer-core/src/cdp/CdpSession.ts:103:29)
              at ExecutionContext.#evaluate (<base-path>/node_modules/puppeteer-core/src/cdp/ExecutionContext.ts:422:44)
              at ExecutionContext.evaluate (<base-path>/node_modules/puppeteer-core/src/cdp/ExecutionContext.ts:293:32)
              at IsolatedWorld.evaluate (<base-path>/node_modules/puppeteer-core/src/cdp/IsolatedWorld.ts:196:26)
              at CdpFrame.evaluate (<base-path>/node_modules/puppeteer-core/src/api/Frame.ts:490:35)
              at CdpFrame.<anonymous> (<base-path>/node_modules/puppeteer-core/src/util/decorators.ts:63:21)
      "name": "TargetCloseError"
    }
```

**Comment by joaosouz4dev** [comment]
This report is now tracked in the cross-repository operational epic: https://github.com/wppconnect-team/.github/issues/3. Keep issue-specific reproduction evidence here; sequencing and shared acceptance criteria live in the epic.
