### ISSUE TITLE
error when setGroupProfilePic

### ISSUE THREAD

**Issue by wduandy** [wppconnect-team/wppconnect#380]
## Log Output

```
error: 2021-07-31T19:00:26.540Z CHAT_JID: invalid jid type: Not an instance of WID - Error: CHAT_JID: invalid jid type: Not an instance of WID
    at t.CHAT_JID (https://web.whatsapp.com/bootstrap_qr.f61502d6311fd24214d7.js:2:560578)
    at t.default (https://web.whatsapp.com/bootstrap_qr.f61502d6311fd24214d7.js:5:84499)
    at Object.t.sendSetPicture (https://web.whatsapp.com/bootstrap_qr.f61502d6311fd24214d7.js:7:132299)
    at Object.<anonymous> (/opt/wppconnect-server2/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:67601)
    at Generator.next (<anonymous>)
    at Qn (/opt/wppconnect-server2/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:67177)
    at a (/opt/wppconnect-server2/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:67381)
    at /opt/wppconnect-server2/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:67442
    at V (https://web.whatsapp.com/bootstrap_qr.f61502d6311fd24214d7.js:2:353842)
    at new v (https://web.whatsapp.com/bootstrap_qr.f61502d6311fd24214d7.js:2:343841)
```

**Comment by edgardmessias** [comment]
Não estou mais aceitando issues sem o devido preencimento, POR FAVOR, o texto no issue não está lá a toa, isso facilita o entendimento do problema e quais os passos para resolve-lo.

![image](https://user-images.githubusercontent.com/1530997/127928300-c1ab13ba-73cd-4407-9549-063b51d5e6f3.png)

Partes em vermelho é para mander, partes em azul para preencher corretamente.
