### ISSUE TITLE
error when addParticipant

### ISSUE THREAD

**Issue by wduandy** [wppconnect-team/wppconnect#381]
## Log Output

```
error: 2021-07-31T19:03:17.209Z Unexpected null or undefined: bundle.encKey - Error: Unexpected null or undefined: bundle.encKey
    at r.default (https://web.whatsapp.com/:2:287)
    at Function.encrypt (https://web.whatsapp.com/bootstrap_main.0f4eab45314264df4066.js:5:6833)
    at t.default.<anonymous> (https://web.whatsapp.com/bootstrap_main.0f4eab45314264df4066.js:2:102672)
    at t.default.write (https://web.whatsapp.com/bootstrap_qr.f61502d6311fd24214d7.js:2:357993)
    at Object.binSend (https://web.whatsapp.com/bootstrap_main.0f4eab45314264df4066.js:2:88178)
    at https://web.whatsapp.com/bootstrap_main.0f4eab45314264df4066.js:2:51120
    at V (https://web.whatsapp.com/bootstrap_qr.f61502d6311fd24214d7.js:2:353842)
    at new v (https://web.whatsapp.com/bootstrap_qr.f61502d6311fd24214d7.js:2:343841)
    at Object.setGroupParticipants (https://web.whatsapp.com/bootstrap_main.0f4eab45314264df4066.js:2:50919)
    at Object.addParticipants (https://web.whatsapp.com/bootstrap_main.0f4eab45314264df4066.js:2:30313)
```

**Comment by edgardmessias** [comment]
Não estou mais aceitando issues sem o devido preencimento, POR FAVOR, o texto no issue não está lá a toa, isso facilita o entendimento do problema e quais os passos para resolve-lo.

![image](https://user-images.githubusercontent.com/1530997/127928300-c1ab13ba-73cd-4407-9549-063b51d5e6f3.png)

Partes em vermelho é para mander, partes em azul para preencher corretamente.
