### ISSUE TITLE
Error when I trying to retrieve old messages

### ISSUE THREAD

**Issue by tadeubdev** [wppconnect-team/wppconnect#433]
## Description

When I trying to retrieve the old messages, I receive this output error.

## Environment

- **Wppconnect** version(s): 1.8.11, 1.8.12
- **Browser**: Chromium 92.0.4515.131 (Official Build) (64-bit)
- **OS**: Ubuntu 20.04.02 LTS
- **Node version**: Node 12.16.1

## Steps to Reproduce

```js
client.getAllUnreadMessages()
```

## Log Output

```
{"name":"Server5xxDrop","stack":"Server5xxDrop\n    at new i (https://web.whatsapp.com/bootstrap_qr.f61502d6311fd24214d7.js:2:382908)\n    at new p (https://web.whatsapp.com/bootstrap_qr.f61502d6311fd24214d7.js:7:67766)\n    at Object.on5xx (https://web.whatsapp.com/bootstrap_qr.f61502d6311fd24214d7.js:18:536442)\n    at Object.onMessage (https://web.whatsapp.com/bootstrap_qr.f61502d6311fd24214d7.js:18:537634)\n    at Object._onParsedMsg (https://web.whatsapp.com/bootstrap_qr.f61502d6311fd24214d7.js:23:17354)\n    at Object._onMessage (https://web.whatsapp.com/bootstrap_qr.f61502d6311fd24214d7.js:23:16962)"}
```

**Comment by edgardmessias** [comment]
I made some tests and it is working file, could you update to `1.8.13` and check it?

**Comment by tadeubarbosa** [comment]
I'll update and try it!
