### ISSUE TITLE
Problemas com alguns metodos que funcionavam antes (BETA Multi-device)

### ISSUE THREAD

**Issue by rodd1981** [wppconnect-team/wppconnect#438]
## Description

Crash quando utilizo métodos que antes funcionavam normalmente:

demoteParticipant
promoteParticipant
sendLinkPreview

## Environment

- **Wppconnect version(s):** 1.8.13 (BETA Multi-device)
- **Browser:** Chromium 91.0.4472.101
- **OS:** Ubuntu 18.04
- **Node version:** 7.20.6

## Steps to Reproduce

Chamar os métodos listados acima.

## Log Output

Error: Unexpected null or undefined: BUNDLE
    at t.default (https://web.whatsapp.com/bootstrap_qr.f61502d6311fd24214d7.js:19:289425)
    at Object.t.get (https://web.whatsapp.com/bootstrap_qr.f61502d6311fd24214d7.js:19:317412)
    at Function.encrypt (https://web.whatsapp.com/bootstrap_main.0f4eab45314264df4066.js:5:6792)
    at t.default.<anonymous> (https://web.whatsapp.com/bootstrap_main.0f4eab45314264df4066.js:2:102672)
    at t.default.write (https://web.whatsapp.com/bootstrap_qr.f61502d6311fd24214d7.js:2:357993)
    at Object.binSend (https://web.whatsapp.com/bootstrap_main.0f4eab45314264df4066.js:2:88178)
    at https://web.whatsapp.com/bootstrap_main.0f4eab45314264df4066.js:2:51120
    at V (https://web.whatsapp.com/bootstrap_qr.f61502d6311fd24214d7.js:2:353842)
    at new v (https://web.whatsapp.com/bootstrap_qr.f61502d6311fd24214d7.js:2:343841)
    at Object.setGroupParticipants (https://web.whatsapp.com/bootstrap_main.0f4eab45314264df4066.js:2:50919)

**Comment by rodd1981** [comment]
Removi a versão Beta e reinstalei a versão antiga do WhatsApp e o problema foi resolvido (então acredito que a versão Beta esteja com bugs).
