### ISSUE TITLE
Getting app crashed from nodemon

### ISSUE THREAD

**Issue by wduandy** [wppconnect-team/wppconnect#445]
## Description

I'm using Wppconnect with MultipleDevices.

## Environment

- **Wppconnect version(s):** 1.8.12
- **Browser:** Chrome 87
- **OS:** Ubuntu 20
- **Node version:** Node 12.22.2

## Steps to Reproduce

I'm not so sure on how to reproduce it. 
But usually i've been using download, forward messages from the server

## Log Output

```
warn:     [mySession:token] Failed to update session token
error: 2021-08-23T19:53:16.561Z Error trying to download the file.
warn: 2021-08-23T19:53:16.564Z Erro ao descriptografar a midia, tentando fazer o download direto...
UnhandledRejection: Error trying to download the file.
    at process.<anonymous> (/opt/wppconnect-server3/node_modules/catch-exit/dist/src/index.js:184:58)
    at process.emit (events.js:314:20)
    at process.EventEmitter.emit (domain.js:483:12)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by edgardmessias** [comment]
@wduandy , could you check it again?
