### ISSUE TITLE
Get Message By Id Error

### ISSUE THREAD

**Issue by makanSukros** [wppconnect-team/wppconnect#467]
## Description

Im cannot get message by id, everything message id always retun error like this

## Environment

- **Wppconnect version(s):**  [1.8.13]
- **Browser:** [Chrome 87]
- **OS:** [ Windows 10]
- **Node version:** [Node 14]
- **WhatsApp version:** [2.2132.6]
- **MultiDevice (BETA):** no

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output
Failed Get Message By Id TypeError: Cannot read property 'match' of undefined
    at new l (https://web.whatsapp.com/bootstrap_qr.99f4f9824125bfd8df54.js:59:25245)
    at o (https://web.whatsapp.com/bootstrap_qr.99f4f9824125bfd8df54.js:59:30126)
    at Function.fromString (https://web.whatsapp.com/bootstrap_qr.99f4f9824125bfd8df54.js:55:298422)
    at Object.<anonymous> (D:\Research\wpp\node_modules\@wppconnect-team\wppconnect\dist\lib\wapi\wapi.js:1:21939)
    at Generator.next (<anonymous>)
    at l (D:\Research\wpp\node_modules\@wppconnect-team\wppconnect\dist\lib\wapi\wapi.js:1:21401)
    at a (D:\Research\wpp\node_modules\@wppconnect-team\wppconnect\dist\lib\wapi\wapi.js:1:21604)
    at D:\Research\wpp\node_modules\@wppconnect-team\wppconnect\dist\lib\wapi\wapi.js:1:21663
    at W (https://web.whatsapp.com/bootstrap_qr.99f4f9824125bfd8df54.js:2:366905)
    at new v (https://web.whatsapp.com/bootstrap_qr.99f4f9824125bfd8df54.js:2:357963)

**Comment by makanSukros** [comment]
Any update on this?

**Comment by edgardmessias** [comment]
I could not reproduce this issue, please, provide an example and reopen
