### ISSUE TITLE
on start 'WAPI is not defined'

### ISSUE THREAD

**Issue by antirek** [wppconnect-team/wppconnect#558]
## Description
`````
[whatsappsession:browser] Initializing browser...
[whatsappsession:client] Initializing...
Status Session:  isLogged
Session name:  whatsappsession
Status Session:  inChat
Session name:  whatsappsession
error on create ReferenceError: WAPI is not defined
    at __puppeteer_evaluation_script__:44:47
    at __puppeteer_evaluation_script__:44:78
    at j (https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:2:379576)
    at new g (https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:2:370471)
    at anonymous (__puppeteer_evaluation_script__:42:14)
[whatsappsession:client] WhatsApp WEB version: 2.2138.13
get instance-state
`````

## Environment

- **Wppconnect version(s):** [1.9.1]
- **Browser:** [e.g. Chrome]
- **OS:** [ubuntu 20.04]
- **Node version:** [Node 14]
- **WhatsApp version:** [2.2138.13]
- **MultiDevice (BETA):** no

**Comment by antirek** [comment]
oh, I check again

And if I set whatsappVersion in config - it's fail, otherwise if I not set whatsappVersion and wppconnect use latest value 2.2138.13 - instance loaded well

**Comment by antirek** [comment]
No. Sometimes all is good with 2.2138.13, sometimes fail with this error.

Maybe increase timeout for evaluate injected code?

**Comment by edgardmessias** [comment]
I think there are some action that is not waiting for JS injection, because the print of whatsapp version occurs after successful injection.
