### ISSUE TITLE
Server5xxDrop on send message

### ISSUE THREAD

**Issue by antirek** [wppconnect-team/wppconnect#624]
when I call sendMessage() receive error
`````
Server5xxDrop
    at new i (https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:2:414484)
    at new p (https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:41:28118)
    at Object.on5xx (https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:55:588481)
    at Object.onMessage (https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:55:589362)
    at Object._onParsedMsg (https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:60:18006)
    at Object._onMessage (https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:60:17612)
`````
what is this mean? no server access?

**Comment by edgardmessias** [comment]
@antirek , could you provide more information?

Normally 5xx erros are server errors

**Comment by ykose1982** [comment]
Same error here...

**Comment by edgardmessias** [comment]
@ykose1982 , could you provide more information?

**Comment by ykose1982** [comment]
> @ykose1982 , could you provide more information?

Today its working fine, it fixed itself. It's ridiculous, I don't fully understand.
