### ISSUE TITLE
verifyNumber Problem

### ISSUE THREAD

**Issue by taknamecom** [wppconnect-team/wppconnect#803]
## Description

Hello My friends.
When I want verifyNumber everything is OK until verifyNumber = false and destination number has not whatsapp.
WPPConnect will be crash and closed.

## Environment

- **Wppconnect version(s):** [e.g. 2.0.27, 2.2.1]
- **Node version:** [Node 16]
- **WhatsApp version:** [2.2126.14]
- **MultiDevice (BETA):** no

## Steps to Reproduce

verifyNumber

## Log Output

EphemeralDrop: query,disappearing_mode
    at new i (https://web.whatsapp.com/bootstrap_qr.37dacf21ec9d2c474b8e.js:2:452434)
    at new _ (https://web.whatsapp.com/bootstrap_qr.37dacf21ec9d2c474b8e.js:61:24365)
    at y.sendEphemeral (https://web.whatsapp.com/bootstrap_qr.37dacf21ec9d2c474b8e.js:56:575697)
    at Object.<anonymous> (https://web.whatsapp.com/bootstrap_main.d600dc4f1c8c09c11723.js:2:81551)
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.fac97d8af22734ef1183.js:2:63784)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.fac97d8af22734ef1183.js:2:63995)
    at V (https://web.whatsapp.com/bootstrap_qr.37dacf21ec9d2c474b8e.js:2:390373)
    at MutationObserver.K (https://web.whatsapp.com/bootstrap_qr.37dacf21ec9d2c474b8e.js:2:389952)
cleanup

**Comment by taknamecom** [comment]
this problem is on /getProfilePic too.
if destination number has not registered on whatsapp. WPPConnect will be crash.

**Comment by edgardmessias** [comment]
@taknamecom , where is the `verifyNumber`? Could you put a small pice of code?

**Comment by taknamecom** [comment]
> @taknamecom , where is the `verifyNumber`? Could you put a small pice of code?

when I want verify number with API ( to check destination number  join to whatsapp or not ) WPPConnect will be crash.
