### ISSUE TITLE
getStatus: e.isUser is not a function

### ISSUE THREAD

**Issue by antirek** [wppconnect-team/wppconnect#804]
## Description

const user = '7913XXXXXXX@c.us';
const contactStatus = await client.getStatus(user);

throw error 

`````
 error contactStatus TypeError: e.isUser is not a function
     at https://web.whatsapp.com/bootstrap_qr.463c81833344582ab256.js:3:152413
     at Generator.next (<anonymous>)
     at t (https://web.whatsapp.com/vendor1~bootstrap_qr.28b6b8e610a5c3159208.js:2:63784)
     at s (https://web.whatsapp.com/vendor1~bootstrap_qr.28b6b8e610a5c3159208.js:2:63995)
     at https://web.whatsapp.com/vendor1~bootstrap_qr.28b6b8e610a5c3159208.js:2:64054
     at x (https://web.whatsapp.com/bootstrap_qr.463c81833344582ab256.js:2:408838)
     at new g (https://web.whatsapp.com/bootstrap_qr.463c81833344582ab256.js:2:404398)
     at https://web.whatsapp.com/vendor1~bootstrap_qr.28b6b8e610a5c3159208.js:2:63935
     at l (https://web.whatsapp.com/bootstrap_qr.463c81833344582ab256.js:3:152968)
     at t.default (https://web.whatsapp.com/bootstrap_qr.463c81833344582ab256.js:3:152260)

`````

## Environment

- **Wppconnect version(s):** [1.12.2]
- **Browser:** [Chrome 97]
- **OS:** [Ubuntu 20.04]
- **Node version:** [Node 14]
- **WhatsApp version:** [2.2149.4]
- **MultiDevice (BETA):** yes

**Comment by edgardmessias** [comment]
Thanks to reporting this @antirek 
You still helping us doing these tests
