### ISSUE TITLE
sendMessage return error: "Module Constants not found"

### ISSUE THREAD

**Issue by antirek** [wppconnect-team/wppconnect#908]
## Description

on client.sendText(chatId, message) error

`````
 error Error: "Module Constants not found with e=>0===e.default.ACK.CLOCK"
     at /usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:103:33
     at step (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
     at Object.next (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
     at fulfilled (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (node:internal/process/task_queues:96:5) 
`````

## Environment

- **WPPConnect version(s):** 1.12.6
- **WA-JS version(s):** 1.1.18
- **Browser:** Chrome 96
- **OS:** Ubuntu 20.04
- **Node version:** Node 16
- **WhatsApp version:** 2.2206.5
- **MultiDevice (BETA):** no

**Comment by antirek** [comment]
also error is repeated on wppconnect 1.12.5

**Comment by antirek** [comment]
if I pass whatsapp web 2.2204.13 - all right

**Comment by edgardmessias** [comment]
Fixed here: https://github.com/wppconnect-team/wa-js/releases/tag/v1.1.19

Pease, update `@wppconnect/wa-js` to 1.1.19
