### ISSUE TITLE
Module randomMessageId not found

### ISSUE THREAD

**Issue by antirek** [wppconnect-team/wppconnect#941]
## Description
on await client.sendText(chatId, message) receive error

`````
 err: {
  name: 'Error',
  message: '"Module randomMessageId not found with e=>e.randomId"',
  err: Error: "Module randomMessageId not found with e=>e.randomId"
      at /usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:103:33
      at step (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
      at Object.next (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
      at fulfilled (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

`````

## Environment

- **WPPConnect version(s):** 1.12.7
- **WA-JS version(s):** 1.2.0
- **Browser:** Chrome 98
- **OS:** Ubuntu 20.04
- **Node version:** Node 16
- **WhatsApp version:** 2.2208.7
- **MultiDevice (BETA):** no

**Comment by edgardmessias** [comment]
Fixed with WA-JS 1.2.1
