### ISSUE TITLE
TypeError: Cannot read property 'meta' of undefined

### ISSUE THREAD

**Issue by sirtonhao** [wppconnect-team/wppconnect#943]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **WPPConnect version(s):** 1.12.7
- **WA-JS version(s):** 1.12.7
- **Browser:** Chrome ultima versão
- **OS:** Windows 10 
- **Node version:** Node 14.18.2
- **WhatsApp version:** BETA Multidevice
- **MultiDevice (BETA):** yes

## Steps to Reproduce

pelo próprio postman ao executar o chatwoot ele aparece isso, tá tudo configurado, inclusive até os dockers tá fazendo isso

## Log Output

```
info: 2022-03-10T23:13:55.647Z Started Session: fixo
TypeError: Cannot read property 'meta' of undefined
    at chatWoot (C:\xampp\htdocs\backzap\servidorzap\src\controller\deviceController.js:669:39)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by antirek** [comment]
is it wppconnect code? show code from 669 line
