### ISSUE TITLE
multidevice: Module sendQueryExists not found 

### ISSUE THREAD

**Issue by antirek** [wppconnect-team/wppconnect#985]
## Description

await client.checkNumberStatus(chatId)

`````
Error: "Module sendQueryExists not found with e=>{var t,r;return(null===(t=e.default)||void 0===t?void 0:t.toStrin
g().includes(\"Should not reach queryExists MD\"))||(null===(r=e.queryExists)||void 0===r?void 0:r.toString().includes(\"Should not reach queryExists MD\"))}"
     at /usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:106:31
     at step (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
     at Object.next (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
     at fulfilled (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
 JS Stack: Error: "Module sendQueryExists not found with e=>{var t,r;return(null===(t=e.default)||void 0===t?void 0:t.toS
tring().includes(\"Should not reach queryExists MD\"))||(null===(r=e.queryExists)||void 0===r?void 0:r.toString().includes(\"Should not reach queryExists MD\"))}"
     at /usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:103:33
     at step (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
     at Object.next (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
     at fulfilled (/usr/src/app/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
`````

## Environment

- **WPPConnect version(s):** 1.12.8
- **WA-JS version(s):** 1.2.2
- **Browser:** Chrome 99
- **OS:** Ubuntu 20.04
- **Node version:** Node 16
- **WhatsApp version:** 2.2210.9
- **MultiDevice (BETA):** yes

**Comment by edgardmessias** [comment]
@antirek , please, update your WA-JS to >= v1.2.4 - `npm install @wppconnect/wa-js@latest`

**Comment by antirek** [comment]
Ok, great thanks, Edgard  @edgardmessias 

I use in package.json only one dependency from @wppconnect-team/wppconnect and I think that wa-js is sub dependency.
